# Generated by Django 4.2.1 on 2023-06-05 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('task', models.TextField()),
                ('is_closed', models.BooleanField(default=False)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeemodel')),
            ],
        ),
    ]
